### ISSUE TITLE
[ExoBundle] Visualisation des questions à partir de la banque de questions

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1220]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

En cliquant sur le titre de la question dans la banque de questions :

[2016-09-23 12:07:18] php.CRITICAL: Fatal Error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Claroline\CoreBundle\Twig\WorkspaceAccessExtension::isDateAccessValid() must be an instance of Claroline\CoreBundle\Entity\Workspace\Workspace, null given, called in /home/hevinci/claroline/app/cache/prod/twig/67/67c6b4405543a050131d59e779daeba2a7793b1e87b5593b66ddd100cc142b8f.php on line 58 and defined' in /home/hevinci/claroline/vendor/claroline/distribution/main/core/Twig/WorkspaceAccessExtension.php:72 Stack trace: #0 /home/hevinci/claroline/vendor/claroline/distribution/main/core/Twig/WorkspaceAccessExtension.php(72): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/hevinci/c...', 72, Array) #1 /home/hevinci/claroline/app/cache/prod/twig/67/67c6b4405543a050131d59e779daeba2a7793b1e87b5593b66ddd100cc142b8f.php(58): Claroline\CoreBundle\Twig\WorkspaceAccessExtension->isDateAccessValid(NULL) #2 /home/hevinci/claroline/app/cache/prod/classes {"type":1,"file":"/home/hevinci/claroline/app/cache/prod/classes.php","line":5313,"level":6143,"stack":[]} []

**Comment by clarophil** [comment]
ok après mise à jour du master

**Comment by clarophil** [comment]
Plus moyen d'ouvrir les questions sur la master travis
