### ISSUE TITLE
[Corebundle] Import : replace UID in src of image

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#883]
At the export of claro v1, I can export all files (html, img,...) and replace src with UID present in the manifest but at the import in claroline connect, the UID present in the html files, aren't replace by the new url of the images.  
This works with the txt files but not the html files.

**Comment by ngodfraind** [comment]
Can you send me the archive / show me the v1 course ?

**Comment by clarophil** [comment]
Sended by email

**Comment by clarophil** [comment]
Je viens de tester avec ce zip et je vois toujours le UID dans le texte à la place de l'image
[TESTEXPORT.zip](https://github.com/claroline/Distribution/files/474587/TESTEXPORT.zip)

**Comment by ngodfraind** [comment]
Il y a un flag non documenté à activer dans le fichier app/config/platform_options.yml.
Il s'agit de 'enable_rich_text_file_import'.

C'est comme ça car la fonction n'est vraiment pas performante.

**Comment by clarophil** [comment]
J'ai changé le paramètre mais j'ai une erreur en important repris dans le message ci-dessus


[2016-10-03 09:54:23] php.CRITICAL: Fatal Error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Claroline\CoreBundle\Repository\ResourceNodeRepository::findByWorkspaceAndMimeType() must be an instance of Claroline\CoreBundle\Entity\Workspace\Workspace, null given, called in /home/hevinci/claroline/vendor/claroline/distribution/main/core/Library/Transfert/ConfigurationBuilders/Tools/Resources/FileImporter.php on line 164 and defined' in /home/hevinci/claroline/vendor/claroline/distribution/main/core/Repository/ResourceNodeRepository.php:549 Stack trace: #0 /home/hevinci/claroline/vendor/claroline/distribution/main/core/Repository/ResourceNodeRepository.php(549): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/hevinci/c...', 549, Array) #1 /home/hevinci/claroline/vendor/claroline/distribution/main/core/Library/Transfert/ConfigurationBuilders/Tools/Resources/FileImporter.php(164): Claroline\CoreBundle\Repository\ResourceNodeRepository->f {"type":1,"file":"/home/hevinci/claroline/app/cache/prod/classes.php","line":5313,"level":6143,"stack":[]} []

**Comment by clarophil** [comment]
Je n'ai pas testé sur la dernière version du master, je testerai après la prochaine maj.   je clos pour le moment donc.
